name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 生成依赖文件
        run: echo "requests" > requirements.txt

      - name: 安装全部依赖
        run: pip install --upgrade 'flet[all]' -r requirements.txt

      - name: 构建APK安装包
        run: |
          #!/bin/bash
          yes | flet build apk --module-name 123

      - name: 上传APK产物
        uses: actions/upload-artifact@v4
        with:
          name: APK安装包
          path: build/apk/*.apk
